# Generated by Django 6.1 on 2026-08-31 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fulfillment_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('failed', 'Failed')], default='not_applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method_detail',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency_code',
            field=models.CharField(default='NGN', max_length=10),
        ),
        migrations.CreateModel(
            name='TransactionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('initialized', 'Checkout Initialized'), ('verify_attempted', 'Verification Attempted'), ('verify_succeeded', 'Verification Succeeded'), ('verify_failed', 'Verification Failed'), ('webhook_received', 'Webhook Received'), ('webhook_rejected', 'Webhook Rejected (Bad Signature)'), ('credit_fulfilled', 'Credit Applied to Meter'), ('fulfillment_failed', 'Credit Application Failed'), ('duplicate_ignored', 'Duplicate Event Ignored (Idempotency)')], max_length=30)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='payments.transaction')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
