# Generated by Django 6.1 on 2026-08-25 16:35

import django.db.models.deletion
import meters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='desired_relay_state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='device_key',
            field=models.CharField(default=meters.models.generate_device_key, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='last_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='last_energy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='last_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='last_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TelemetryReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
                ('power', models.FloatField()),
                ('energy', models.FloatField()),
                ('relay_state', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='meters.meter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
