# Generated by Django 6.1 on 2026-08-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0002_meter_desired_relay_state_meter_device_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='low_credit_threshold',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
    ]
