# Generated by Django 6.1 on 2026-09-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0003_meter_low_credit_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='offline_alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
